# Worksheet 1

First worksheet for COMSM0075 Information processing and the brain

In [35]:
import math
import numpy as np
from numpy import where

## Q1

Work out the marginal probability distribution and conditional distributon

In [99]:
D = np.array([
    [1/16, 1/2],
    [0, 1/4],
    [1/16, 1/8]
])

# marginal distribution from l to r: 1, 2, 3, a, b
D.sum(1), D.sum(0)

(array([0.5625, 0.25  , 0.1875]), array([0.125, 0.875]))

In [100]:
# condition distribution P(Y|X=a)

p_x_given_a = D[:,0]

p_x_given_a / p_x_given_a.sum()

array([0.5, 0. , 0.5])

## Q2

Work out entropy

In [101]:
# H(X)

X_d = D.sum(0)

# - (1/16+1/16)*log2(1/16*1/16) + (1/2+1/4+1/8)*log2(1/2+1/4+1/8)

# -(X_d * np.log2(X_d)).sum()

X_d

array([0.125, 0.875])

In [29]:
# H(Y)

Y_d = D.sum(1)

-(Y_d * np.log2(Y_d)).sum()

1.4197367178034825

In [46]:
# H(X|Y)

D_given_y = np.vstack((
    D[0,:] / D[0,:].sum(),
    D[1,:] / D[1,:].sum(),
    D[2,:] / D[2,:].sum()
))

-(D * where(D_given_y != 0, np.log2(D_given_y), 0)).sum()

<ipython-input-46-03259b292c3a>:9: RuntimeWarning: divide by zero encountered in log2
  -(D * where(D_given_y != 0, np.log2(D_given_y), 0)).sum()


0.45526328219651757

In [49]:
# H(Y|X)

# First work out probability distribution for P(Y|X)
D_given_x = np.column_stack((
    D[:,0] / D[:,0].sum(),
    D[:,1] / D[:,1].sum()
))

# Then work out the multiplications of all entries with their log2
-(D * where(D_given_x != 0, np.log2(D_given_x), 0)).sum()

<ipython-input-49-3d13e0f6c0c0>:8: RuntimeWarning: divide by zero encountered in log2
  -(D * where(D_given_x != 0, np.log2(D_given_x), 0)).sum()


1.3314355568004037

In [50]:
# H(X,Y)

-(D * where(D != 0, np.log2(D), 0)).sum()

<ipython-input-50-a614d13ef225>:3: RuntimeWarning: divide by zero encountered in log2
  -(D * where(D != 0, np.log2(D), 0)).sum()


1.875

In [52]:
# H(Y) - H(Y|X)

H_y = -(Y_d * np.log2(Y_d)).sum()
H_y_given_x = -(D * where(D_given_x != 0, np.log2(D_given_x), 0)).sum()

H_y - H_y_given_x

<ipython-input-52-b0dc808c005a>:4: RuntimeWarning: divide by zero encountered in log2
  H_y_given_x = -(D * where(D_given_x != 0, np.log2(D_given_x), 0)).sum()


0.08830116100307883

In [53]:
# I(X;Y) huh

## Q3

Working out entropy (pt 2?)

In [102]:
D = np.array([
    [1/2**4,1/2**4],
    [4*1/2**5,4*1/2**5],
    [10*1/2**6,10*1/2**6],
    [20*1/2**7,20*1/2**7]
])

D_per_series = np.array([
    [1/16],
    [1/32],
    [1/64],
    [1/128]
])

In [103]:
# H(X)

X_d = D.sum(1)
-(X_d * np.log2(D_per_series.T)).sum()

5.8125

In [104]:
# H(Y)

Y_d = D.sum(1)

-(Y_d * np.log2(Y_d)).sum()

1.9237949406953985

In [108]:
# H(X|Y)

(-(X_d * np.log2(D_per_series.T)).sum()) - (-(Y_d * np.log2(Y_d)).sum())

3.8887050593046015

In [109]:
# H(Y|X) is equal to 0 since the outcome determines the series length

0

0

## Q4

The average entropy

For a distribution with two events $\{x_1,x_2\}$

$p(x_1)=p$ and $p(x_2)=1-p$, under the assumption that each value of $p$ is equally likely

---

$H(X) = - (p \times \log_2 p + 1-p \times \log_" 1-p)$

To get the average entropy we need

$\displaystyle\langle H\rangle_p \int_0^1 H(p)\text{ dp} = - \int_0^1p\log p\text{ dp}-\int_0^1(1-p)\log(1-p)\text{ dp}$

Given that the choice of which probability to call $p$ and which to call $1-p$ you may expect that the two are equal

$\displaystyle\int_0^1p\log p\text{ dp} = \int_0^1(1-p)\log(1-p)\text{ dp}$

This is easy to check by substituting $q=1-p$. Hence:

$\displaystyle\langle H\rangle_p = -2 \int_0^1 p\log p\text{ dp}$

To make the integration easier, let us switch to natural log

$\displaystyle\langle H_e\rangle_p = -2 \int_0^1 p\ln p\text{ dp}$

It is easy to convert back since $\log p = \frac{\ln p}{\ln 2}$. Now use integration by parts with $u = \log p$ and $\text{dv} = p\text{ dp}$

$\displaystyle\int_0^1 p\ln p\text{ dp} = \frac{p^2}{2}\ln - \int_0^1\frac{p^2}{2}\frac{1}{p}\text{ dp} = \frac{p^2}{4}_0^1 = -\frac{1}{4}$

Therefore:

$\displaystyle -2 \times -\frac{1}{4} = \frac{1}{2}$

and hence:

$\displaystyle\langle H\rangle_p\frac{1}{2\ln 2}\approx 0.72$